name: CI

on: workflow_dispatch

jobs:
  build-installers:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - run: go version
      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: nightly
          docker_nightly_version: snapshot-20201008
      - run: docker version
      - run: go get github.com/karalabe/xgo
      - run: docker pull karalabe/xgo-latest
      - run: |
          cd ~/go/src
          git clone https://github.com/OneKeyHQ/onekey-bridge trezord-go
          cd trezord-go/release
          GOPATH=~/go make all